### ISSUE TITLE
PDF for download?

### ISSUE THREAD

**Issue by dakom** [getify/Functional-Light-JS#105]
Is there a tool for generating a pdf to read offline?

**Comment by getify** [comment]
That is not provided by this repo but there are such tools available if you do google searches. The official ebook (PDF/mobi/etc) will be published for sale through leanpub, while the markdown on this repo will remain free to read forever.

**Comment by dakom** [comment]
Awesome! Didn't realize there was a "notify me when this is ready" button over there on the Leanpub site. I bought all your YDKJS series in paper form, would love to buy this too! I know this is the worst thing to ask anyone - but, any ETA?

**Comment by getify** [comment]
I hope sometime in July to have the final published work released. I just got sooo busy I've been swamped for months with no time to finish up the edits.
