### ISSUE TITLE
Chinese translation complete

### ISSUE THREAD

**Issue by JoeHetfield** [getify/Functional-Light-JS#106]
Hi, Kyle.

I'm glad to tell you that the Chinese translation of the main text of Functional-Light-JS had complete:

[This is the repo](https://github.com/JoeHetfield/Functional-Light-JS)

Just like YDKJS, it will be a Chinese mirror of your master branch.

The translation of appendix (a little difficult to me, I need more time to study on it) and preface still in progress,  hopefully finished within next month.

Please tell me what you think.

**Comment by maczyt** [comment]
Thx. ^_&

**Comment by getify** [comment]
Just heads up, there's lots of inbound edits (including some reorg of chapters). Keep an eye on the following commits. :)

**Comment by JoeHetfield** [comment]
Sure, please keep me update.

**Comment by getify** [comment]
Hey @joehetfield the first edition is finally complete and stable. Please feel free to get your Chinese translation updated now, and let me know when it's time to merge back into this repo. :)

**Comment by JoeHetfield** [comment]
Great！Chinese translation will be finished next month. I will comment here when it been done.

**Comment by JoeHetfield** [comment]
Hi, Kyle. I'm glad to tell you that the Chinese translation has been fully updated and ready for shoot !

**Comment by getify** [comment]
@JoeHetfield Fantastic! I've added you as a collaborator and created the "1ed-zh-CN" branch for you to merge your translation into.

**Comment by JoeHetfield** [comment]
PR is on the way

**Comment by getify** [comment]
As a collaborator, you should be able to review the PR (looks like there are conflicts) and merge when ready.

**Comment by JoeHetfield** [comment]
OK, I'll solve the conflicts and merge. thanks!

**Comment by JoeHetfield** [comment]
Hi, Kyle. Merge complete!
Now the FLJS has a Chinese mirror! 😄

**Comment by getify** [comment]
Sweeeeeet! Thanks so much!
