### ISSUE TITLE
Redundant fns.slice() in compose example

### ISSUE THREAD

**Issue by EvgenyOrekhov** [getify/Functional-Light-JS#111]
In https://github.com/getify/Functional-Light-JS/blob/master/ch4.md#general-composition you have this piece of code:

```js
function compose(...fns) {
	return function composed(result){
		// copy the array of functions
		var list = fns.slice();
```

Why copy the `fns` array if it's local to the `compose` function? Nobody outside `compose` can have a reference to it.

**Comment by getify** [comment]
It's not redundant, it's very necessary. But it's a bit sneaky why.

> Nobody outside compose can have a reference to it.

That's the part that's sneaky. `composed(..)` (which is the returned composed function) has a reference to it, and for this particular implementation, `composed(..)` mutates the list with `.pop(..)`. This is a problem if you try to use the returned composed function more than once.

Here's proof:

![screen shot 2017-09-08 at 7 49 51 am](https://user-images.githubusercontent.com/150330/30212460-bbeb0638-946a-11e7-82dc-d34c527a85ed.png)

The `list = fns.slice()` ensures in the original code listing ensures **each time** that `fns` isn't modified, so the composed function can keep being used as often as needed.

**Comment by EvgenyOrekhov** [comment]
@getify Got it! Thank you for a prompt and detailed explanation!

**Comment by getify** [comment]
See above commit: I took this opportunity to call out this point of confusion you brought up. It's subtle enough that it deserves direct attention. Thanks!
