### ISSUE TITLE
Applied FP / Popmotion

### ISSUE THREAD

**Issue by Martin-Pitt** [getify/Functional-Light-JS#114]
I've been using Popmotion recently with great delight. I've always struggled to get into FP in a way that felt meaningful or with a library that I could apply a lot of the learnings of light FP with.

Would you mind taking a look and see how it fits/relates with your book? It might offer a good way for some/few readers to exercise/apply their knowledge.

Sorry, if this is rude or I've misunderstood. I'm still paging through the chapters and also picking up popmotion at the same time, but couldn't help draw useful parallels between the two that really excite me :)

**Comment by getify** [comment]
Link?

**Comment by Martin-Pitt** [comment]
@getify
Main site: https://popmotion.io/
Intros to how it uses FP: https://popmotion.io/learn/value-pipelines/
Low-level docs: https://popmotion.io/api/

**Comment by getify** [comment]
The "value-pipelines" page is cool. All that stuff sounds heavily compatible with the style of FP presented in this book. :)

**Comment by getify** [comment]
Thanks for the tip!
