### ISSUE TITLE
Copyediting suggestions for Appendix B

### ISSUE THREAD

**Issue by jtassia** [getify/Functional-Light-JS#131]
Query: 

Original: "Here's a simple implementation:"

Kyle: Could we swap "simple" with "basic" here?  To avoid repetition of simple (in the last sentence of previous para we say "instead, I'm going to stick with just a simple function approach.").  

**Yes, I promise I've read the [Contributions Guidelines](https://github.com/getify/Functional-Light-JS/blob/master/CONTRIBUTING.md)**

**Comment by getify** [comment]
> Could we swap "simple" with "basic" here?

Sure!

**Comment by jtassia** [comment]
Done!
