### ISSUE TITLE
Copyediting suggestions for Appendix C

### ISSUE THREAD

**Issue by jtassia** [getify/Functional-Light-JS#132]
Just one query for this appendix...

Original: "Again, there will inevitably be cases where whether concurrent or serial asynchrony will be called for."

Query: Should "whether" be removed here?  Or is there something missing?

**Yes, I promise I've read the [Contributions Guidelines](https://github.com/getify/Functional-Light-JS/blob/master/CONTRIBUTING.md)**

**Comment by getify** [comment]
> Should "whether" be removed here?

Yep!

**Comment by jtassia** [comment]
Done!
