### ISSUE TITLE
Chapter 7, Grammar Error?

### ISSUE THREAD

**Issue by newyork-anthonyng** [getify/Functional-Light-JS#139]
Current:
> If you think about it as "turtles (aka, objects) all the way down", at the lowest level, all state data **_is_** primitives, and all primitives are value-immutable.

Should be:
> If you think about it as "turtles (aka, objects) all the way down", at the lowest level, all state data **_are_** primitives, and all primitives are value-immutable.

**Comment by getify** [comment]
I don't think "data" is universally accepted as a plural. See: http://www.quickanddirtytips.com/education/grammar/is-data-singular-or-plural?page=1

The usage of "all" here might imply plurality, but my intent is "all *of the* state data is...", however I left out "of the" just for brevity/informality sake.

However, the plural "primitives" here is the most compelling evidence of a mismatch. Yet, I would still assert "data" should be singular. Here's why: the sentence reads in my mind (aka, is intended as): "...at the lowest level, all *of the* state data is *comprised of* primitives..."

Leaving out those two connective phrases does introduce a slight amount of grammar ambiguity, but I think it's mostly just being picky to insist on them being there to justify the *is* vs *are* choice. While I strive to be grammatically correct (for the most part!), I also have an informal style that I think can afford a few liberties like this one. :)

Thanks for the input, though!

**Comment by newyork-anthonyng** [comment]
@getify Makes sense 👍 

Thanks again for your hard work! It's a great read.
