### ISSUE TITLE
Problem with partialRight ?

### ISSUE THREAD

**Issue by solendil** [getify/functional-light-js#14]
In Chapter 3, "All For One", you say :

```javascript
["1","2","3"].map( parseInt );
// [1,NaN,NaN]
["1","2","3"].map( unary( parseInt ) );
// [1,2,3]
```

And this scan also be solved with `partialRight(parseInt,10)`.

However, when I tested it:

```javascript
["1","2","3"].map( partialRight(parseInt,10) );
// [1,NaN,NaN]
```

I believe it's because `partialRight` does _append_ its partial argument to the end of the arguments list. It couldn't _replace_ arguments (the radix in this case) because it has no sense of arity.

**Comment by getify** [comment]
Great point, thanks! Will fix.

**Comment by solendil** [comment]
Oh and there's another occurrence later in "No Points"
