### ISSUE TITLE
Testimonials

### ISSUE THREAD

**Issue by getify** [getify/Functional-Light-JS#140]
If you've read at least several chapters of this book, and liked it so far, I need your help!

I need a few quotes/testimonials. What I need is a 1-3 sentence (<150 words) quote from you about the book/topic, why you have found it useful, any positive impacts it's had on your coding, etc. I also need your name/job-title as you'd like to be attributed.

By replying to this thread, you are agreeing to let me use some or all of what you submit in marketing for the book, including but not limited to, the book cover, this repository, the twitter account, any future book website, etc.

**Comment by justsml** [comment]
In FLJS Kyle Simpson uses his prolific understanding of JavaScript and Functional Programming to bring these important concepts to the JavaScript world.

**Comment by Attrash-Islam** [comment]
I've been coding for almost more than 4 years, I wrote huge AngularJS 1.x apps, and recently React apps, I've been up-to-date of all articles and online courses as much as possible (Absolutely Geek!), but I can say for sure that the FLJS book is mind-blowing! I almost lost my mind with the concepts it explains! This book give me the right way of understanding concepts more than focusing on Frameworks! Thanks @getify :heart:

**Comment by hanneslund** [comment]
By focusing on concepts instead of terminology i feel much more confident in my understanding of the foundations of functional programming.  I feel motivated and excited to dive even deeper!

**Comment by getify** [comment]
thanks, these are great! keep 'em coming!

**Comment by getify** [comment]
@hanneslund Can I please have your full name/title so I can attribute your quote?

**Comment by hanneslund** [comment]
@getify Hannes Lund, software developer

**Comment by getify** [comment]
@Attrash-Islam I need your full name/title as well, please. :)

**Comment by Attrash-Islam** [comment]
@getify My full name is: Islam Attrash, and I'm Full stack JavaScript Engineer, working primarily with TypeScript and React, previously on AngularJS 1.x, and has 4 years of experience in the client-side world

**Comment by getify** [comment]
@hanneslund @Attrash-Islam psssst... here's the draft of the print-cover: https://github.com/getify/Functional-Light-JS/blob/master/manuscript/images/marketing/print-book-cover.png :)

**Comment by hanneslund** [comment]
@getify Cool, looking good :)

**Comment by Attrash-Islam** [comment]
@getify Thanks, I feel honored to be on such a book ❤❤

**Comment by DmitriWolf** [comment]
Nobody explains JavaScript as well as Kyle Simpson. He is as thorough as he is humble, explaining complex ideas in simple language. Kyle makes learning JavaScript easy without skipping the details. 
~ Dmitri Wolf, Front End Developer, IBM

**Comment by getify** [comment]
@DmitriWolf Thanks so much, that's really kind of you to say! :)

**Comment by darkamenosa** [comment]
After reading this book, I finally found the reason why I should use functional programming. Although I'm experienced in using list operators, the chapter 9 gave me a new point of view to use them better. I would recommend this book to my coworkers. Thanks @getify! 
~ Tuyen Ho, Full-Stack Developer, Grande JSC.
