### ISSUE TITLE
Future

### ISSUE THREAD

**Issue by ulfryk** [getify/Functional-Light-JS#141]
Hey, nice job!

I just wanted to say that maybe https://github.com/fluture-js/Fluture is also worth mentioning in the `Appendix C: FP Libraries`…

**Comment by getify** [comment]
Appreciate the suggestion... I decided to stay away from Fantasy-Land (ironically, same acronym: FL) stuff for this book. I think that stuff is too intense for my intended audience.

**Comment by ulfryk** [comment]
Reasonable decision :)
