### ISSUE TITLE
why favor old style loops over (es5) alternatives?

### ISSUE THREAD

**Issue by SanderElias** [getify/functional-light-js#17]
I'm reading trough the chapters as you are putting them on. I really like what I'm reading.
Just wondering why you favor (for brevity sake I'm just using the ES6 arrow function in stead of the full versions) this:

```
  var uncurry =
       fn =>
           (...args) => {
               var ret = fn;

               for (let i = 0; i < args.length; i++) {
                   ret = ret( args[i] );
               }

               return ret;
           };

```

over:

```
const uncurry = fn => 
    (...args) => 
       args.reduce(
            (ret,cur) => ret(cur),
            fn
       );
```

The `.map()`, `.reduce()` and so on seem a much better fit to explain a functional coding style.

**Comment by getify** [comment]
Those haven't been introduced in the text yet.... whole chapter on list operations. Trying to avoid using stuff that hasn't yet been explained.

**Comment by SanderElias** [comment]
Ok, that makes sense.
