### ISSUE TITLE
Chapter 9: Mismatch in map parameters.

### ISSUE THREAD

**Issue by infinityfye** [getify/Functional-Light-JS#172]
In the [Map](https://github.com/getify/Functional-Light-JS/blob/master/manuscript/ch9.md/#map) section of Chapter 9, after the implementation of `map` you give a note on parameter order, the example given has the parameters in the wrong order.
```javascript
map( ["1","2","3"], unary( parseInt ) );
// [1,2,3]
```
I believe it should be
```javascript
map(unary( parseInt ),  ["1","2","3"] );
// [1,2,3]
```
Please forgive me if I'm mistaken.

**Comment by getify** [comment]
You're correct, thanks for catching that!

**Comment by infinityfye** [comment]
The parameter ordering mismatch is also echoed in the first example in [Method Vs Standalone](https://github.com/getify/Functional-Light-JS/blob/master/manuscript/ch9.md/#method-vs-standalone) section. The current code is
```javascript
[1,2,3,4,5]
.filter( isOdd )
.map( double )
.reduce( sum, 0 );                  // 18

// vs.

reduce(
    map(
        filter( [1,2,3,4,5], isOdd ),
        double
    ),
    sum,
    0
);                                  // 18
```
I believe it should be
```javascript
[1,2,3,4,5]
.filter( isOdd )
.map( double )
.reduce( sum, 0 );                  // 18

// vs.

reduce(
    sum,
    0,
    map(
        double,
        filter( isOdd, [1,2,3,4,5] )
    )
);                                  // 18
```
I realise that this is mostly to point out the difference in the API, which is why I didn't create a new Issue.
