### ISSUE TITLE
Image tag not closing

### ISSUE THREAD

**Issue by xorob0** [getify/Functional-Light-JS#180]
**Yes, I promise I've read the [Contributions Guidelines](https://github.com/getify/Functional-Light-JS/blob/master/CONTRIBUTING.md)** (please feel free to remove this line -- if you leave this line here, I'm going to assume you didn't actually read it).

Some reader don't like that the img tag are not closed. I would advise changing this : 
```
<p align="center">
    <img src="images/fig1.png" width="40%">
</p>
```
to this : 
```
<p align="center">
    <img src="images/fig1.png" width="40%"/>
</p>
```
on every images.
I can do a the PR if you want me to, but maybe there is a reason for that that I do not understand.

**Comment by getify** [comment]
> Some reader don't like that the img tag are not closed

Why?

**Comment by xorob0** [comment]
If you try converting them to XHTML (for ePub for exemple) you need the self-closing tag because it is in the XHTML specifications it is needed (see https://www.w3schools.com/tags/tag_img.asp)
My kobo e-reader really doesn't like that the tag is not closed and just skips the rest of the chapter...

**Comment by getify** [comment]
Interesting... I wonder why the epub that is generated from Leanpub works fine. Maybe they're correcting it.
