### ISSUE TITLE
 a closure associates a single function with a set of state

### ISSUE THREAD

**Issue by a-c-sreedhar-reddy** [getify/Functional-Light-JS#186]
This statemet is not correct I guess.

> a closure associates a single function with a set of state, whereas an object holding the same state can have any number of functions to operate on that state

```
function closur(){
  let i = 0;
  return {
   add : ()=>i++,
   sub : ()=>i--
 }
```
Here two functions are assosiated with a state.
Correct me if my understanding is wrong.

**Comment by getify** [comment]
Yes, there are two functions, and thus two closures, each closed over the same shared state.

**Comment by a-c-sreedhar-reddy** [comment]
Then 

> a closure associates a single function with a set of state, whereas an object holding the same state can have any number of functions to operate on that state

is this statement which I found in book wrong?

**Comment by getify** [comment]
I think you're reading too much into the statement. The intent is not to imply that a function closure is mutually exclusive of another function closure. It's to point out that closure is over private state, so only the function(s) closed over it can access it, where as an object is public state and any function at any time can access it.

**Comment by a-c-sreedhar-reddy** [comment]
Thank for the book.:heart:

I also heard FP helps scalability. If possible can you just brief about that in the book.
