### ISSUE TITLE
Chapter 9: not getting the standalone implementation reducer function

### ISSUE THREAD

**Issue by qianist** [getify/Functional-Light-JS#188]
**Quote:**

But a standalone implementation of `reduce(..)` might look like this:

```javascript
function reduce(reducerFn,initialValue,arr) {
    var acc, startIdx;

    if (arguments.length == 3) {
        acc = initialValue;
        startIdx = 0;
    }
    else if (arr.length > 0) {
        acc = arr[0];
        startIdx = 1;
    }
    else {
        throw new Error( "Must provide at least one value." );
    }

    for (let idx = startIdx; idx < arr.length; idx++) {
        acc = reducerFn( acc, arr[idx], idx, arr );
    }

    return acc;
}
```

**Question:**

Perhaps I don't understand the context, but how to call this function without passing an initialValue?

**Comment by baekhyunee7** [comment]
maybe some details is omitted,rewrite it ```else if (arr=initialValue,arr.length > 0) {```

**Comment by kyletannv** [comment]
From [Appendix A](https://github.com/getify/Functional-Light-JS/blob/40a68612275b23904c7b37abdb724b250bdf75e7/manuscript/apC.md?plain=1#L193):

> With traditional library implementations of reduce(..) (like Ramda), the initial value parameter is in the middle, and not optional.

His library ([FPO](https://github.com/getify/fpo)) makes it optional:

> FPO's reduce(..) method can take the arguments in any order, and you can omit the optional initial value if desired.
