### ISSUE TITLE
partialRight utility seems to have issue

### ISSUE THREAD

**Issue by Etherum7** [getify/Functional-Light-JS#196]
It is written

> The value "z:last" is only applied to the z parameter in the case where f(..) is called with exactly two arguments (matching x and y parameters). In all other cases, the "z:last" will just be the rightmost argument, however many arguments precede it.

but when only one argument is passed as in the second example the "z:last" is not assigned to the right most arguments.

![image](https://user-images.githubusercontent.com/58840954/92686707-ce799400-f357-11ea-8eda-1beefe9a5b8b.png)

**Comment by getify** [comment]
```js
f(1);  // 1 "z:last"
```

Here `"z:last"` ***is*** the "rightmost argument" (aka "the last argument")... Note that I didn't say "rightmost parameter". In a variadic-functions language, you are free to pass as few or as many arguments as you want no matter how many parameters are declared. This utility (as with pretty much all others) is applying its logic to the arguments, not the parameter; a function can't really pragmatically self-inspect its own definition to apply logic based on declared parameters.
