### ISSUE TITLE
Concerning "Functions vs. Procedures"

### ISSUE THREAD

**Issue by booc0mtaco** [getify/functional-light-js#2]
Just reading the content you've added so far. This will be good, so thank you!

Wondering if you plan to bring up the side-effects part of functions versus procedures. Would that fit into that early section on the differences between the two? I could imagine it:

## Excerpt (with added example):

You're probably most used to thinking of functions as general procedures. What is a procedure? An arbitrary collection of functionality. It may have inputs, it may not. It may have an output (return value), it may not. **It may have side effects outside its operating scope, it may not.**

But a function specifically takes input(s), and definitely has a return value. **And, it always produces the same output when given the same input.**

Hopefully not jumping in too early with this suggestion! If this isn't precisely part of the difference between the two, I'd like to know more about it, as I've always understood it to be core.

**Comment by getify** [comment]
There will be a whole section, maybe even a whole chapter, on side effects and avoiding them (pure functions). Here, I'm going to only briefly note the idea that all input should be passed in as arguments and all output should come out in the return value. I'll leave the explanation of the whys of that to that later section/chapter.

Thanks!

**Comment by booc0mtaco** [comment]
Makes sense to me!
