### ISSUE TITLE
In depth use of partial - chapter 3

### ISSUE THREAD

**Issue by pertrai1** [getify/functional-light-js#20]
You make it a point to understand the partial function, and i find that it would be good to get an understanding of a use case of how it would be used. 

> When the partiallyApplied(..) function is later executed somewhere else in your program, it uses the closed over fn to execute the original function, first providing any of the (closed over) presetArgs partial application arguments, then any further laterArgs arguments.

**Comment by getify** [comment]
Did you read further and find that the explanation was sufficient?

**Comment by pertrai1** [comment]
Yeah I got overzealous in stopping where you said to stop and understand. At that point I felt I needed to see it in action to fully understand. Read a bit further and then did see it being used.
