### ISSUE TITLE
Unassigned variables should be compared to undefined rather than null

### ISSUE THREAD

**Issue by jtrimble** [getify/Functional-Light-JS#24]
Yes, I promise I've read the [Contributions Guidelines](CONTRIBUTING.md).

Admittedly, this is a minor quibble. But since this is a teaching text I'll mention it for your consideration.

In Chapter 2, the section on early returns, your example program that has been refactored to have a single return, gates each assignment to retValue with an if (retValue == null && ...). Since no assignment has ever been made to retValue, it's actual value is undefined and it is coerced into a null by the equality operator. This works, but seems unnecessarily fragile when you could either explicitly set retValue = null in your declaration, or you could compare directly to undefined. Any time == would cause my program to do one thing and === would cause my program to do another, I become a little concerned.

**Comment by getify** [comment]
Thanks for the feedback... I'll take it into consideration. :)

**Comment by gagyibenedek** [comment]
One more thing to add: why are you doing the retValue == undefined check in the first if? The var was not used yet, so it'll always be undefined.

**Comment by getify** [comment]
for symmetry sake.

**Comment by gagyibenedek** [comment]
hmm, that's a strange reasoning. Why give the reader and the cpu an extra thing to process and think about, when it's not needed?

**Comment by getify** [comment]
think of it this way: with early-return style, you can just insert a new line of return code anywhere, even at the top of the function, and not have to change any other lines of code.

if the first IF doesn't have the undefined check, then there's a refactoring hazard in that respect. I think it's better to prevent rather than trip over it.
