### ISSUE TITLE
Sign up for Editing assistance

### ISSUE THREAD

**Issue by mindpivot** [getify/Functional-Light-JS#27]
Filing an issue to to track those who would like to volunteer to assist with editing. Kyle works very hard on these books and contributes volumes to the community, let's give him a hand!

If you'd like to help, this is the place to make that fact known!

**Comment by rkichenama** [comment]
I volunteer as tribute... to help edit

**Comment by aarondolson** [comment]
I'm happy to help

**Comment by getify** [comment]
The main chapters (1-11) are now draft complete.

If you're interested in doing some editing, please go ahead and do so! Just file one issue per chapter with any feedback you may have. Add additional comments as you get more feedback on the chapter. :)

**Comment by nick-walt** [comment]
I would like to help with editing and will bring a beginner's mind to the editing (I know that this book isn't for beginners, but if something can be stated more simply or directly I can possibly help there).

Aside from helping with editing, the biggest thing from a beginner's perspective, and something that I constantly stuggle with, is understanding when to use OO and when to use FP *and, most importantly, how to combine them*.

**Comment by getify** [comment]
The book is now draft-complete (chapters and appendices). Now's the time if anyone wants to help with review comments. We expect to wind down formal editing in the next 2 weeks or so. Thanks! :)

**Comment by getify** [comment]
Calling @raganwald would you be willing to do some review? please!? :)
