### ISSUE TITLE
Publish to Medium?

### ISSUE THREAD

**Issue by datwheat** [getify/Functional-Light-JS#29]
Is it possible to publish a version of this book to Medium.com for easier consumption? I loved reading YDKJS, but from a consumption POV it was really hard to read as well as hard to keep my place on on GitHub. I know this may be asking for a bit for a free book, but I believe it would benefit your audience.

**Comment by getify** [comment]
The book will not be published to Medium. However, I may put it on gitbook (undecided yet). TBH, though, the intent of the repo is to provide the content for collaboration. It's not a "free book". If you want the good reading experience, I prefer you purchase the book (once it's available), which will likely be through something like Leanpub.

**Comment by vincent-louis** [comment]
@getify, thanks for the completing the book. Frankly, gitbook reading experience is much better than leanpub, unless we manually download epub and import them to other application like iBook, no luck for window user like me.
