### ISSUE TITLE
Add additional resource

### ISSUE THREAD

**Issue by InceptionCode** [getify/Functional-Light-JS#41]
Hey, @getify I recently emailed you about my repo [ Functional-Programming-Exercises](https://github.com/InceptionCode/Functional-Programming-Exercises) and was asked to file this issue. I would love for my repo to be a useful resource to help new developers, like myself, learn functional programming. 

Please, when you have the time review the code, make suggestions, and send requests over so my repo can be a more suitable guide for beginners in FP.

- [ ] Add repo to README, and possibly Chapter 1 "resources"

**Comment by getify** [comment]
Thanks, haven't forgotten about this, will work on it when I get a chance.

**Comment by InceptionCode** [comment]
Thank you @getify this means a lot to me.
