### ISSUE TITLE
Careful about explaining currying

### ISSUE THREAD

**Issue by shajra** [getify/functional-light-js#6]
This quote is wrong and misleading:

> Currying is a special form of partial application where the arity is reduced to 1, with a chain of successive chained function calls, each which takes one argument. 

Currying is not at all a special form of partial application.  Some people get currying and partial application confused because in languages like Haskell, functions are curried by default, which is convenient for partial application.

What currying is much more simple.  It's merely this:

curry :: ((a, b) -> c) -> (a -> b -> c)

This leads to another concern I have with your pedagogy.  To get to a syntactic convenience, you go over techniques well beyond FP, like reflecting over the arity of a function.  This makes currying seem much more fancy that it really is conceptually.  My recommendation is to explain the basics with just the basics.  Then find a way to layer on complexity more incrementally.  You may not get to the slick API immediately, in exchange people may track better with the concepts you're trying to teach.

That said, I think Chapter 1 is just too long, and goes too deep into the nuances Ecmascript's function implementation.  Just to start with, I'd recommend just showing people the bare minimum to play around with a lambda calculus in a REPL.  That makes the discussion of simple combinators like curry, uncurry, flip, etc, much more tidy.

**Comment by shajra** [comment]
Hey, I really hope you didn't take offense to the phrase "wrong and misleading."  I didn't mean it at all as a personal attack, and in retrospect I would make my point with different words.  Teaching is hard, and from what I can tell, you're trying to hear out people with different perspectives.

And if I really want to teach something in a different way, I do have the option of making my own markdown files in my own repository.

People do learn in different ways.  Some methods of teaching are kind of commensurate.  Some of definitely ill-advised.  We just have to do our best figuring this all out with limited data and feedback.

**Comment by getify** [comment]
Thanks very much, I appreciate your sentiment and candor. And I do appreciate help in making the text better. I hope that feedback can be discussed in a non-combative and constructive way instead of as a "you suck at this". I hope the commit I did helped to clarify the text to address some of your concerns around `partial(..)` vs `curry(..)`, and I welcome any future constructive feedback you may have. :)
