### ISSUE TITLE
Development Edit, Chapter 5

### ISSUE THREAD

**Issue by bmacdonald-editor** [getify/Functional-Light-JS#62]
I went over Chapter 5 multiple times, because I wasn't finding as much to say about it as I had the previous four, and that worried me. However, after reading the next several chapters, I think from this point on, the writing really hits a groove, and there isn't as much to say from a development standpoint. The organization is clear and strong, and easy to follow.

## Once Is Enough, Thanks section
This section is all about defining what "idempotence" means, both mathematically and programmatically, but if the reader has no assumptions about the word coming in, it can be hard to get through the discussion. I think it would help to provide a "common definition" of idempotence in the first paragraph or two, for those readers who haven't encountered the concept.

## Performance Effects section
Is performance the only consideration for "pragmatic referential transparency"? It's certainly important, but I got the impression that there might be other reasons for "pragmatic" referential transparency that aren't discussed. If not, then so be it.

## `this` Revisited section
I suggest promoting this heading to level 2. It's not really a subset of "Evading Effects," it's another variation, as you say in the first sentence.

**Comment by peterse40** [comment]
I'm not interested.   
  
  
  

  
  

  
  
>
