### ISSUE TITLE
typos Ch7

### ISSUE THREAD

**Issue by happysalada** [getify/Functional-Light-JS#82]
There a couple of typos on the page
`cull` -> `call` (most probably)
also an opening bracket missing after the last()
```
var person = {
	firstName: "Kyle",
	lastName: "Simpson",
	first() {
		return this.firstName;
	},
	last()
		return this.lastName;
	}
}
```

**Comment by getify** [comment]
Thanks!

**Comment by getify** [comment]
`cull` isn't a typo there: http://www.dictionary.com/browse/cull
