### ISSUE TITLE
Open for translations?

### ISSUE THREAD

**Issue by zhouyao** [getify/Functional-Light-JS#97]
Simplified Chinese translation

**Comment by zhouyao** [comment]
Could we translate “Functional-Light-JS” into simplified Chinese and share with more Chinese developers? 

We are looking forward to hearing from you.

our organization：https://github.com/ikcamp

**Comment by getify** [comment]
I already have someone doing the Chinese translations for this book. Thanks!

https://github.com/getify/Functional-Light-JS/issues/106

**Comment by zhouyao** [comment]
https://github.com/ikcamp/Functional-Light-JS

totally complete.
